"""Initial models 2

Revision ID: aa3416cabbc0
Revises: b09da87d51c2
Create Date: 2024-11-01 11:32:19.645453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa3416cabbc0'
down_revision: Union[str, None] = 'b09da87d51c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Referral', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key('Ref', 'Referral', 'Users', ['owner_id'], ['id'])
    op.add_column('Users', sa.Column('referrer_code_id', sa.Integer(), nullable=True))
    op.create_foreign_key('User', 'Users', 'Referral', ['referrer_code_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('User', 'Users', type_='foreignkey')
    op.drop_column('Users', 'referrer_code_id')
    op.drop_constraint('Ref', 'Referral', type_='foreignkey')
    op.drop_column('Referral', 'owner_id')
    # ### end Alembic commands ###
