name: referral_system
services:
  db:
    image: postgres:latest
    container_name: db_app
    env_file:
      - .env-non-dev
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: referral_app
    command: ['/referral_system/docker/command.sh']
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  pgdbdata: {}

